### PR TITLE
Workaround Pri.LongPath regression on DirectoryInfo.Exists.

### PR DESCRIPTION
**Pull request by azchohfi**
Temporary workaround for #15 until https://github.com/peteraritchie/LongPath/issues/82 is fixed

### CODE REVIEW

**Comment by azchohfi** [comment]
@devlead Is this project still being managed?

**Comment by devlead** [comment]
Yes

**Comment by devlead** [comment]
@azchohfi your changes have been merged, thanks for your contribution 👍

**Comment by azchohfi** [comment]
Awesome! Thanks!

**Comment by azchohfi** [comment]
https://github.com/peteraritchie/LongPath/issues/82 have been fixed. We can bump the dependency and revert this commit.

**Pull request merged**
